name: jason_2
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  json_annotation: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.7.0
  json_serializable: ^0.3.1

flutter:
  uses-material-design: true